name: Build Slurm Packages
on:
  push:
  workflow_call:
jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          version:
            - 22.04
            - 24.04
    container:
      image: "ubuntu:${{ matrix.version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Packages
        run: |
          apt update && apt -y install curl make
          make build-ubuntu
      - name: Create build artifact
        uses: actions/upload-artifact@master
        with:
          name: ubuntu-${{ matrix.version }}-debs
          path: /build/*.deb
  rocky-build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          version:
            - 9
    container:
      image: "rockylinux:${{ matrix.version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Packages
        run: |
          dnf -y install make
          make build-rocky
      - name: Create build artifact
        uses: actions/upload-artifact@master
        with:
          name: rocky-${{ matrix.version }}-rpms
          path: /root/rpmbuild/RPMS/x86_64/*.rpm
