name: Build RPMs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          platform:
            - ubuntu:22.04
            - ubuntu:24.04
    container:
      image: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Packages
        uses: addnab/docker-run-action@v3
        with:
          image: "${{ matrix.platform }}"
          options: "-v ${{ github.workspace }}:/src"
          run: |
            apt update && apt -y install curl make
            make build-ubuntu
