name: Build Ubuntu Packages
on:
  push:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          version:
            - 22.04
            - 24.04
    container:
      image: "ubuntu:${{ matrix.version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: debug
        run: id
      - name: Build Packages
        run: |
          id
          apt update && apt -y install curl make
          make ubuntu-build
      - name: Create build artifact
        uses: actions/upload-artifact@master
        with:
          name: ubuntu-debs-${{ matrix.version }}
          path: /build/*.deb
