name: Build RPMs

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          platform:
            - ubuntu:2204
            - ubuntu:2404
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download Slurm source
        run: "bash -c 'make prep-host'"
      - name: Build Packages
        uses: addnab/docker-run-action@v3
        with:
          image: "${{ matrix.platform }}"
          options: "-v ${{ github.workspace }}:/src"
          run: "bash -c 'make build-ubuntu'"
